let a = 10;
let b = 5;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a > b);
console.log(a == b);
console.log(a > 5 && b < 10);
console.log(a > 20 || b < 10);